#storePassword=chullbullott
#keyPassword=chullbullott
#keyAlias=upload
#storeFile=/Users/anilkhandelwal/chullbull.jks
storeFile=upload-keystore-chulltv.jks
storePassword=chullbullott
keyPassword=chullbullott
keyAlias=upload