#storePassword=chullbullott
#keyPassword=chullbullott
#keyAlias=upload
#storeFile=/Users/anilkhandelwal/chullbull.jks
storeFile=upload-keystore-chulltv.jks
storePassword= chulltvott
keyAlias= upload
keyPassword= chulltvott