// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd6LG1t7GZeU2Sq6kptlHNOX1WMvYeH18',
    appId: '1:151680591442:web:96ce3e2fdd00a25008e18b',
    messagingSenderId: '151680591442',
    projectId: 'omtv-32b09',
    authDomain: 'omtv-32b09.firebaseapp.com',
    storageBucket: 'omtv-32b09.appspot.com',
    measurementId: 'G-BVB05REQVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7DiHnMvE0UreF6EzIvWTs3Ngpk-1tY0',
    appId: '1:151680591442:android:4b413fb786f96b6c08e18b',
    messagingSenderId: '151680591442',
    projectId: 'omtv-32b09',
    storageBucket: 'omtv-32b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMMc6MEdaWKFd0BItzZA3WicBzW_CG3s',
    appId: '1:151680591442:ios:663569928e856e2e08e18b',
    messagingSenderId: '151680591442',
    projectId: 'omtv-32b09',
    storageBucket: 'omtv-32b09.appspot.com',
    iosBundleId: 'com.ott.omtvapp.ott',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMMc6MEdaWKFd0BItzZA3WicBzW_CG3s',
    appId: '1:151680591442:ios:f7aade1cc3c5723e08e18b',
    messagingSenderId: '151680591442',
    projectId: 'omtv-32b09',
    storageBucket: 'omtv-32b09.appspot.com',
    iosBundleId: 'com.ott.omtvappapp',
  );
}
